export const items = [

	{
		id: 1,
		itemName: 'Quesadilla de porotos negros y pimientos',
		stock: 20,
		price: 400,
		shortDescription: 'con Salsa Fresca & Guacamole Cremoso',
		description: 'Si ya eres fan de las quesadillas, esta es para ti. Repleto de pimiento verde tierno, sabroso puré de frijoles negros y toneladas de queso pegajoso y derretido, es bastante irresistible, y eso es antes de que se cubra con salsa fresca picante y cucharadas de guacamole cremoso. Sí, algo bueno acaba de mejorar mucho.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/quesadilla_porotos_negros_pimientos_ha3wdz.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669977974/veggieBox/img/dishes/525x350/quesadilla_porotos_negros_pimientos_qnobgf.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669980669/veggieBox/img/dishes/750x500/quesadilla_porotos_negros_pimientos_wu3ocv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840882/veggieBox/img/dishes/310x207/quesadilla_porotos_negros_pimientos_rcigkz.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Pimiento Verde', 'Eschalote', 'Tomate', 'Lima', 'Mezcla de especias', 'Porotos negros', 'Guacamole', 'Crema agria', 'Tortillas de harina', 'Mezcla de Quesos', 'Queso Tybo' ],
		cookingTime: 25,
		cookingDifficulty: 'Sencillo',
		nVcalories: '840 kcal',
		nVfat: '44g',
		nVsaturatedFat: '18g',
		nVcarbohydrate: '82g',
		nVsugar: '7g',
		nVdietaryFiber: '14g',
		nVprotein: '28g',
		nVcholesterol: '60mg',
		nVsodium: '1.440mg',
	},
	{
		id: 2,
		itemName: 'Salteado de cerdo con pimientos dulces y repollo',
		stock: 20,
		price: 400,
		shortDescription: 'con “Arroz” de Coliflor & Cebollitas Fritas Crujientes',
		description:
			'¿Caer en la rutina de saltear con la misma combinación de vegetales y salsa cada semana? Te tenemos cubierto. Esta versión presenta carne de cerdo molida con ajo, que se cuece a fuego lento en una mezcla dulce, salada y picante de soja, ponzu, salsa de chile tailandés y vinagre de vino de arroz. Se mezcla con col tierna salteada, luego se coloca sobre arroz Jazmín y se adorna con cebollas fritas crujientes. ¿La mejor parte? Toma solo 20 minutos de principio a fin; eso es lo que llamamos una cena ganadora.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/salteado_cerdo_pimientos_dulces_repollo_eqvx2n.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669980737/veggieBox/img/dishes/525x350/salteado_cerdo_pimientos_dulces_repollo_qr8mb9.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669980669/veggieBox/img/dishes/750x500/salteado_cerdo_pimientos_dulces_repollo_adukpy.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840926/veggieBox/img/dishes/310x207/salteado_cerdo_pimientos_dulces_repollo_jmmmb8.jpg',
		],
		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Arroz Jazmín', 'Eschalote', 'Glaseado de soja dulce', 'Salsa dulce de chile tailandés', 'Salsa Ponzu', 'Vinagre de arroz', 'Carne de cerdo molida', 'Polvo de ajo', 'Mezcla de col morada y zanahoria', 'Cebollas Fritas Crujientes', 'Arroz de Coliflor' ],
		cookingTime: 20,
		cookingDifficulty: 'Sencillo',
		nVcalories: '700 kcal',
		nVfat: '43g',
		nVsaturatedFat: '16g',
		nVcarbohydrate: '46g',
		nVsugar: '31g',
		nVdietaryFiber: '5g',
		nVprotein: '26g',
		nVcholesterol: '110mg',
		nVsodium: '1.450mg',
	},
	{
		id: 3,
		itemName: 'Bifes balsámicos y Papas al horno',
		stock: 20,
		price: 400,
		shortDescription: 'con Salsa Balsámica de Arándanos',
		description:
			'¿Caer en la rutina de saltear con la misma combinación de vegetales y salsa cada semana? Te tenemos cubierto. Esta versión presenta carne de cerdo molida con ajo, que se cuece a fuego lento en una mezcla dulce, salada y picante de soja, ponzu, salsa de chile tailandés y vinagre de vino de arroz. Se mezcla con col tierna salteada, luego se coloca sobre arroz jazmín y se adorna con cebollas fritas crujientes. ¿La mejor parte? Toma solo 20 minutos de principio a fin; eso es lo que llamamos una cena ganadora.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/bifes_balsamicos_papas_al_horno_up641y.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669982923/veggieBox/img/dishes/525x350/bifes_balsamicos_papas_al_horno_qbprex.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669982965/veggieBox/img/dishes/750x500/bifes_balsamicos_papas_al_horno_vwr7uv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840724/veggieBox/img/dishes/310x207/bifes_balsamicos_papas_al_horno_ryrcbq.jpg',
		],
		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Solomillo', 'Vinagre balsámico', 'Salsa de soja', 'Patatas Yukón Doradas', 'Romero', 'Cebolla amarilla', 'Repollo rojo rallado', 'Semillas de mostaza', 'Vinagre de vino blanco', 'Mermelada de arándano' ],
		cookingTime: 40,
		cookingDifficulty: 'Sencillo',
		nVcalories: '535 kcal',
		nVfat: '15g',
		nVsaturatedFat: '3g',
		nVcarbohydrate: '59g',
		nVsugar: '15g',
		nVdietaryFiber: '8g',
		nVprotein: '45g',
		nVcholesterol: '95mg',
		nVsodium: '840mg',
	},
	{
		id: 4,
		itemName: 'Buñuelos de Garbanzos al Curry',
		stock: 20,
		price: 400,
		shortDescription: 'con Arroz Pilaf de Espinacas, Pasas en Escabeche y Salsa Cremosa de Ajo',
		description:
			'Es difícil NO amar un ingrediente que ha sido frito. Este está inspirado en los sabores tradicionales de la India y está protagonizado por garbanzos, triturados y luego mezclados con una masa ligera de tempura especiada con curry. Fritos al estilo panqueque hasta que estén crujientes, los buñuelos se combinan con nuestros acompañamientos favoritos: pilaf de arroz esponjoso con espinacas, pasas en escabeche y una llovizna de salsa cremosa de ajo. ¡Ahora, intente poner un poco de todo en su tenedor a la vez para crear el bocado perfecto!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/bunuelos_de_garbanzos_al_curry_e2sgwj.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669985232/veggieBox/img/dishes/525x350/bunuelos_de_garbanzos_al_curry_ub9e5c.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669985276/veggieBox/img/dishes/750x500/bunuelos_de_garbanzos_al_curry_slpw0c.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840758/veggieBox/img/dishes/310x207/bunuelos_de_garbanzos_al_curry_fknzhd.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Garbanzos', 'Mezcla Tempura', 'Cebolla morada', 'Polvo de curry', 'Eschalote', 'Arroz basmati', 'Yogur', 'Crema agria', 'Limón', 'Ajo', 'Pasas doradas', 'Espinaca', 'Anacardos', 'Concentrado de caldo de verduras' ],
		cookingTime: 40,
		cookingDifficulty: 'Difícil',
		nVcalories: '970 kcal',
		nVfat: '35g',
		nVsaturatedFat: '10g',
		nVcarbohydrate: '144g',
		nVsugar: '27g',
		nVdietaryFiber: '14g',
		nVprotein: '25g',
		nVcholesterol: '30mg',
		nVsodium: '2.060mg',
	},
	{
		id: 5,
		itemName: 'Tagliatelle Cremoso De Camarones',
		stock: 20,
		price: 400,
		shortDescription: 'con Tomates Perita cremosos, Ajo y Chile',
		description:
			'¡Pronto! ¡Pronto! Puedes hacer esta receta para la cena con la velocidad del rayo de un auto de carreras italiano. Gracias a los tagliatelle frescos, que se cocinan más rápido que los secos, se llega a la perfección al dente en cuestión de minutos. Los camarones y los tomates reliquia solo necesitan un rápido lanzamiento en la sartén, y se vuelven tiernos a la cuenta de uno, due, tre.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187572/veggieBox/img/dishes/100x90/tagliatelle_cremoso_de_camarones_qeivft.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669989479/veggieBox/img/dishes/525x350/tagliatelle_cremoso_de_camarones_tvsh94.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669989468/veggieBox/img/dishes/750x500/tagliatelle_cremoso_de_camarones_mirxsy.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840978/veggieBox/img/dishes/310x207/tagliatelle_cremoso_de_camarones_gtyuuj.jpg',
		],

		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Ajo', 'Eschalot', 'Ají picante', 'Tomates ', 'Uva', 'Limón', 'Camarone', 'Pasta Tagliatelle', 'Crema agria' ],
		cookingTime: 20,
		cookingDifficulty: 'Sencillo',
		nVcalories: '750 kcal',
		nVfat: '27g',
		nVsaturatedFat: '12g',
		nVcarbohydrate: '86g',
		nVsugar: '9g',
		nVdietaryFiber: '5g',
		nVprotein: '50g',
		nVcholesterol: '350mg',
		nVsodium: '880mg',
	},
	{
		id: 6,
		itemName: 'Wraps veganos de lechuga y garbanzos al curry',
		stock: 20,
		price: 400,
		shortDescription: 'con Batata, Porotos y Salsa de Pimiento Rojo y Cilantro',
		description:
			'Si ha estado en la línea de solicitud de ideas para cenas ligeras, sabrosas, satisfactorias y veganas, esta es para usted. Primero aplastará los garbanzos (para crear bordes dentados para dorar) y los asará con camote, comino y curry hasta que estén crujientes, luego agregue los guisantes salteados, la cebolla, el ajo, el jengibre y un poco de limón. Rellene toda esa bondad cálida en hojas de lechuga frescas y crujientes, rocíe con una salsa picante de pimiento rojo y cilantro y es música vegana envolvente para sus papilas gustativas.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187572/veggieBox/img/dishes/100x90/wraps_veganos_de_lechuga_y_garbanzos_al_curry_b37bqp.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669991019/veggieBox/img/dishes/525x350/wraps_veganos_de_lechuga_y_garbanzos_al_curry_jbjrvg.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670004433/veggieBox/img/dishes/750x500/wraps_veganos_de_lechuga_y_garbanzos_al_curry_migynd.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670841093/veggieBox/img/dishes/310x207/wraps_veganos_de_lechuga_y_garbanzos_al_curry_tfbxb5.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Garbanzos', 'Batata', 'Comino', 'Polvo de curry', 'Cebolla amarilla', 'Cilantro', 'Limón', 'Ajo', 'Jengibre', 'Lechuga Bebé', 'Guisantes', 'Mermelada de Pimientos Rojos' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '590 kcal',
		nVfat: '13g',
		nVsaturatedFat: '1g',
		nVcarbohydrate: '102g',
		nVsugar: '36g',
		nVdietaryFiber: '16g',
		nVprotein: '18g',
		nVcholesterol: '0mg',
		nVsodium: '880mg',
	},
	{
		id: 7,
		itemName: 'Chili de carne y porotos negros a la olla',
		stock: 20,
		price: 400,
		shortDescription: 'con Crema Picante Suave y Queso Tybo',
		description:
			'Un buen chili tiene carne de res bien condimentada, frijoles cremosos y vegetales tiernos. Sin embargo, un gran chile tiene todo eso y se junta en una olla en menos de una hora. Este chile es uno de los grandes. Y una vez que le des un mordisco, podemos garantizarte que estarás de acuerdo. Sin mencionar que estos tazones fornidos están adornados con deliciosos acompañamientos: crema de salsa picante picante y Monterey Jack derretido. Si tiene algunos a mano, ¿por qué no desmenuzar algunos chips de tortilla y espolvorearlos encima para que queden crujientes?',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/chili_de_carne_y_porotos_negros_a_la_olla_uoww6p.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669991877/veggieBox/img/dishes/525x350/chili_de_carne_y_porotos_negros_a_la_olla_l237hg.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669991855/veggieBox/img/dishes/750x500/chili_de_carne_y_porotos_negros_a_la_olla_wp0p3a.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840778/veggieBox/img/dishes/310x207/chili_de_carne_y_porotos_negros_a_la_olla_tyg3bt.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Cebolla amarilla', 'Jalapeño', 'Carne molida', 'Mezcla de Especias Mexicanas', 'Mezcla de especias del suroeste', 'Pasta de tomate', 'Tomates', 'Porotos negros', 'Concentrado de caldo de res', 'Crema agria', 'Salsa picante', 'Queso Tybo' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '780 kcal',
		nVfat: '35g',
		nVsaturatedFat: '14g',
		nVcarbohydrate: '53g',
		nVsugar: '18g',
		nVdietaryFiber: '12g',
		nVprotein: '46g',
		nVcholesterol: '125mg',
		nVsodium: '1.000mg',
	},
	{
		id: 8,
		itemName: 'Tostadas de carne con queso',
		stock: 20,
		price: 400,
		shortDescription: 'con Pimiento Verde, Salsa de Tomate y Crema de Salsa Picante',
		description:
			'Nos encanta un buen taco de carne molida, pero no necesita que le digamos cómo hacer uno, hay kits para eso. En cambio, estamos aquí para mostrarte cómo llevar la noche Tex-Mex al siguiente nivel. Entonces ingrese la tostada, que presenta una tortilla plana horneada hasta que esté crujiente, con mucha superficie para apilarla. Afortunadamente, hay muchos aderezos en esta receta, y no solo carne molida con especias cálidas, también hay pimiento verde, salsa de tomate y una crema agria picante.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187572/veggieBox/img/dishes/100x90/tostadas_de_carne_con_queso_wqz1t5.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669996803/veggieBox/img/dishes/525x350/tostadas_de_carne_con_queso_zoz2l9.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669996824/veggieBox/img/dishes/750x500/tostadas_de_carne_con_queso_zkxuig.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670841052/veggieBox/img/dishes/310x207/tostadas_de_carne_con_queso_hqn9et.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Tomate', 'Cilantro', 'Lima', 'Pimiento Verde Largo', 'Cebolla amarilla', 'Crema agria', 'Salsa picante', 'Carne molida', 'Mezcla de especias del suroeste', 'chile en polvo', 'Concentrado de caldo de res', 'Tortillas de harina', 'Mezcla de Quesos Mexicanos' ],
		cookingTime: 40,
		cookingDifficulty: 'Sencillo',
		nVcalories: '950 kcal',
		nVfat: '54g',
		nVsaturatedFat: '24g',
		nVcarbohydrate: '52g',
		nVsugar: '11g',
		nVdietaryFiber: '4g',
		nVprotein: '42g',
		nVcholesterol: '145mg',
		nVsodium: '1.920mg',
	},
	{
		id: 9,
		itemName: 'Tiras de pollo Teriyaki',
		stock: 20,
		price: 400,
		shortDescription: 'con Arroz Jazmín y Arvejas',
		description:
			'¡Soja para el mundo! Ha llegado el momento de una receta simple de salteado de pollo. Estos tiernos se mezclan con un espeso glaseado teriyaki, que cubre cada pieza con una sabrosa mezcla de salsa de soja, ajo, jengibre y sésamo. Servidos sobre una cama de arroz jazmín con judías verdes al lado, aportan un tour-de-force de sabores de estilo asiático que tanto niños como adultos encontrarán fácil de amar.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187572/veggieBox/img/dishes/100x90/tiras_de_pollo_teriyaki_ssquwk.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669997361/veggieBox/img/dishes/525x350/tiras_de_pollo_teriyaki_cgtuty.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669997380/veggieBox/img/dishes/750x500/tiras_de_pollo_teriyaki_queq9z.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670841036/veggieBox/img/dishes/310x207/tiras_de_pollo_teriyaki_wfexds.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Jengibre', 'Ajo', 'Eschalote', 'Lima', 'Arroz Jazmín', 'Arvejas', 'Aceite de sésamo', 'Semillas de sésamo', 'Tiras de pollo', 'Salsa de soja', 'Vinagre de vino blanco', 'Maicena' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '640 kcal',
		nVfat: '15g',
		nVsaturatedFat: '3g',
		nVcarbohydrate: '85g',
		nVsugar: '15g',
		nVdietaryFiber: '4g',
		nVprotein: '44g',
		nVcholesterol: '105mg',
		nVsodium: '860mg',
	},
	{
		id: 10,
		itemName: 'Curry de Coco y garbanzos vegano',
		stock: 20,
		price: 400,
		shortDescription: 'con Arroz Basmati y Gajos de Pita con Ajo',
		description:
			'El curry es una de esas comidas que calienta el corazón y el estómago, y la versión vegana de esta noche no es una excepción. Los garbanzos, la cebolla y los tomates reciben un tratamiento súper sabroso en una salsa de curry cremosa con leche de coco. Vierta toda esta delicia sobre arroz basmati esponjoso, espolvoree con cilantro fresco y sirva con gajos de pita con ajo para absorber el curry. ¡Es una comida que satisface el alma!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/curry_vegano_de_coco_y_garbanzos_xqpp4w.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669998552/veggieBox/img/dishes/525x350/curry_vegano_de_coco_y_garbanzos_zlqzrc.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669998485/veggieBox/img/dishes/750x500/curry_vegano_de_coco_y_garbanzos_whsi2b.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840815/veggieBox/img/dishes/310x207/curry_vegano_de_coco_y_garbanzos_d1fa0i.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Ajo', 'Cebolla morada', 'Garbanzos', 'Perejil', 'Arroz Basmati', 'Chile en polvo', 'Polvo de curry', 'Leche de coco', 'Tomates', 'Concentrado de caldo de verduras', 'Pitas de Trigo Integral' ],
		cookingTime: 35,
		cookingDifficulty: 'Medio',
		nVcalories: '1.000 kcal',
		nVfat: '35g',
		nVsaturatedFat: '16g',
		nVcarbohydrate: '146g',
		nVsugar: '24g',
		nVdietaryFiber: '15g',
		nVprotein: '25g',
		nVcholesterol: '0mg',
		nVsodium: '1.210mg',
	},
	{
		id: 11,
		itemName: 'Salmón con especias toscanas y cuscús con ajo',
		stock: 20,
		price: 400,
		shortDescription: 'con Zuchini Asado y Salsa de Pimiento Rojo picante suave',
		description:
			'¿La pesca de un nuevo giro en el salmón? ¿O incluso una buena idea para un brunch? ¡Tenemos justo lo que necesitas! Los filetes crujientes con piel, sazonados con una especia italiana picante, están cubiertos con una salsa cremosa hecha de mermelada de pimiento rojo, cebolla, crema agria picante y rica mantequilla. A un lado, cuscús israelí elástico y con ajo, calabacín dorado asado y cebolla en rodajas. Si eso no te atrae, ¡no sabemos qué lo hará!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/salmon_con_especias_toscanas_y_cuscus_con_ajo_bmdxzb.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669999374/veggieBox/img/dishes/525x350/salmon_con_especias_toscanas_y_cuscus_con_ajo_mdldge.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1669999402/veggieBox/img/dishes/750x500/salmon_con_especias_toscanas_y_cuscus_con_ajo_yxxbmt.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840907/veggieBox/img/dishes/310x207/salmon_con_especias_toscanas_y_cuscus_con_ajo_jiwfg6.jpg',
		],
		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Ajo', 'Zucchini', 'Cebolla amarilla', 'Cuscús israelí', 'Salmón', 'Especias toscanas', 'Concentrado de Caldo de Pollo', 'Mermelada de Pimiento Rojo', 'Queso crema', 'Crema agria' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '720 kcal',
		nVfat: '43g',
		nVsaturatedFat: '13g',
		nVcarbohydrate: '47g',
		nVsugar: '13g',
		nVdietaryFiber: '3g',
		nVprotein: '37g',
		nVcholesterol: '110mg',
		nVsodium: '520mg',
	},
	{
		id: 12,
		itemName: 'Bibimbap coreano de carne',
		stock: 20,
		price: 400,
		shortDescription: 'con Zuchinni, Champiñones y Zanahoria',
		description:
			'Este plato coreano toma su nombre de la palabra coreana para mezclar arroz. Que es exactamente lo que debes hacer después de servirlo: colocas el arroz en un tazón, agregas los ingredientes y lo mezclas todo para que esos sabores y texturas se combinen en una mezcla gloriosa. Aquí también hay muchos sabores y texturas, como zanahoria dulce, calabacín jugoso y carne de res mezclada con ajo, jengibre y soja.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/bibimbap_coreano_de_carne_gzu3e7.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670005286/veggieBox/img/dishes/525x350/bibimbap_coreano_de_carne_cdbs3r.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670005318/veggieBox/img/dishes/750x500/bibimbap_coreano_de_carne_cwa5mv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840214/veggieBox/img/dishes/310x207/bibimbap_coreano_de_carne_cjlubm.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Zuchinni', 'Champiñones', 'Eschalote', 'Zanahorias', 'Jengibre', 'Ajo', 'Arroz Jazmín', 'Vinagre de vino blanco', 'Aceite de sésamo', 'Sriracha', 'Salsa de soja', 'Carne molida' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '810 kcal',
		nVfat: '36g',
		nVsaturatedFat: '10g',
		nVcarbohydrate: '90g',
		nVsugar: '18g',
		nVdietaryFiber: '5g',
		nVprotein: '35g',
		nVcholesterol: '90mg',
		nVsodium: '1.020mg',
	},
	{
		id: 13,
		itemName: 'Hoagies de Champiñones y Mozzarella',
		stock: 20,
		price: 400,
		shortDescription: 'con Mayonesa de Dijon y Brócoli Sazonado',
		description:
			'Esta semana, un sándwich clásico recibe un giro centrado en las verduras. Los champiñones carnosos se saltean con audaces y sabrosas especias para bistec hasta que quedan crujientes y caramelizados. Luego, se rellenan en baguettes tostadas, junto con una cremosa mayonesa de Dijon, una maraña de pimientos y cebollas, y una capa de mozzarella pegajosa. ¡Agregue sabrosas rodajas de papa y tendrá una comida estilo restaurante!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/hoagies_de_champinones_y_mozzarella_m0k7vb.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670005494/veggieBox/img/dishes/525x350/hoagies_de_champinones_y_mozzarella_ozcojg.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670005416/veggieBox/img/dishes/750x500/hoagies_de_champinones_y_mozzarella_clkgxu.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840848/veggieBox/img/dishes/310x207/hoagies_de_champinones_y_mozzarella_vbl2xq.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Champiñones Cremini', 'Cebolla amarilla', 'Pimiento Verde Largo', 'Papas', 'Aceite en spray', 'Mayonesa', 'Mostaza de Dijon', 'Media baguette', 'Especias para bistec atrevidas y sabrosas', 'Concentrado de caldo de champiñones', 'Queso mozzarella', 'Brócoli' ],
		cookingTime: 35,
		cookingDifficulty: 'Medio',
		nVcalories: '940 kcal',
		nVfat: '47g',
		nVsaturatedFat: '10g',
		nVcarbohydrate: '107g',
		nVsugar: '14g',
		nVdietaryFiber: '9g',
		nVprotein: '25g',
		nVcholesterol: '45mg',
		nVsodium: '1.280mg',
	},
	{
		id: 14,
		itemName: 'Sándwiches de chuleta de cerdo con hierbas',
		stock: 20,
		price: 400,
		shortDescription: 'con Salsa de Cebolla, Gajos de Papas al Limón y Mayonesa de Dijón',
		description:
			'Tienes tu pizza de plato hondo de Chicago y tu perrito caliente al estilo de Chicago, pero ¿conoces el icónico sándwich de chuleta de cerdo de Chicago? Shh, es un pequeño secreto de la ciudad natal de este plato, y esta es una novedosa del súper sabroso clásico. En nuestra versión, chuletas deshuesadas sazonadas y chamuscadas y cebolla en rodajas (¡cocinadas en la grasa de la sartén!) rellenan panecillos tostados untados con Dijonnaise. ¡Los gajos de patata crujientes besados ​​con limón sustituyen a las patatas fritas en esta variación de una sensación de Chi-town!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670007437/veggieBox/img/dishes/525x350/sandwiches_de_chuleta_de_cerdo_con_hierbas_aii8lu.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670007416/veggieBox/img/dishes/750x500/sandwiches_de_chuleta_de_cerdo_con_hierbas_rbmyur.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840949/veggieBox/img/dishes/310x207/sandwiches_de_chuleta_de_cerdo_con_hierbas_xlcaz8.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Papas', 'Cebolla amarilla', 'Limón', 'bollos de patata', 'condimento para freír', 'Mayonesa', 'Mostaza de Dijon', 'Chuletas de Cerdo', 'Sal de apio', 'Tomillo seco', 'Harina', 'Concentrado de Caldo de Pollo' ],
		cookingTime: 35,
		cookingDifficulty: 'Medio',
		nVcalories: '940 kcal',
		nVfat: '52g',
		nVsaturatedFat: '14g',
		nVcarbohydrate: '90g',
		nVsugar: '12g',
		nVdietaryFiber: '6g',
		nVprotein: '35g',
		nVcholesterol: '120mg',
		nVsodium: '1.690mg',
	},
	{
		id: 15,
		itemName: 'Cuencos veganos picantes de coliflor Tex-Mex',
		stock: 20,
		price: 400,
		shortDescription: 'con Fajita de Verduras, Guacamole y Salsa de Ananás',
		description:
			'¿Desea todos los tentadores sabores y texturas de un tazón de arroz, menos la carne? No busque más. Para esta comida vegana inspirada en fajitas tex-mex, construirá su tazón comenzando con una cama de arroz esponjoso con ajo, cilantro y lima, cubierto con cebollas y pimientos caramelizados glaseados con jugo de piña. El siguiente: coliflor asada dulce y picante, guacamole cremoso, salsa picante de piña y un chorrito de lima.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670187571/veggieBox/img/dishes/100x90/cuencos_veganos_picantes_de_coliflor_mex-mex_zpogmx.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670008043/veggieBox/img/dishes/525x350/cuencos_veganos_picantes_de_coliflor_mex-mex_qlusny.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670008089/veggieBox/img/dishes/750x500/cuencos_veganos_picantes_de_coliflor_mex-mex_w6cwlr.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670840797/veggieBox/img/dishes/310x207/cuencos_veganos_picantes_de_coliflor_mex-mex_asiwta.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Coliflor', 'Ajo', 'Pasta Tex-Mex', 'Arroz Jazmín', 'Pimiento Verde Largo', 'Cebolla amarilla', 'Lima', 'Cilantro', 'Ananás', 'Mezcla de especias para fajitas', 'Guacamole' ],
		cookingTime: 35,
		cookingDifficulty: 'Medio',
		nVcalories: '590 kcal',
		nVfat: '20g',
		nVsaturatedFat: '2.5g',
		nVcarbohydrate: '97g',
		nVsugar: '16g',
		nVdietaryFiber: '9g',
		nVprotein: '6g',
		nVcholesterol: '0mg',
		nVsodium: '1.070mg',
	},
	{
		id: 16,
		itemName: 'Sopa vegana de coliflor y frijoles a la olla',
		stock: 20,
		price: 400,
		shortDescription: 'con Chips de Tortilla de Maíz Azul y Cilantro',
		description:
			'Esta abundante y sabrosa sopa vegana está lista en menos de 30 minutos y se cocina en una olla, ¡lo que facilita la limpieza! El coliflor y los frijoles se cuecen a fuego lento en un caldo ricamente especiado (caldo de verduras, cebolla, pimiento verde, tomates y condimentos del sudoeste) hasta que estén tiernos. Adorne con cilantro fresco y sirva chips de tortilla de maíz azul crujientes para una cena SOUP-er.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670649150/veggieBox/img/dishes/100x90/sopa_vegana_de_coliflor_y_frijoles_a_la_olla_akdtp7.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670649232/veggieBox/img/dishes/525x350/sopa_vegana_de_coliflor_y_frijoles_a_la_olla_rwixnr.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670649278/veggieBox/img/dishes/750x500/sopa_vegana_de_coliflor_y_frijoles_a_la_olla_cjkpdv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670649194/veggieBox/img/dishes/310x207/sopa_vegana_de_coliflor_y_frijoles_a_la_olla_wwkauo.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Cebolla amarilla', 'Pimiento Verde Largo', 'Tomate', 'Floretes de coliflor', 'Mezcla de especias del suroeste', 'Pasta de tomate', 'Frijoles negros', 'Pasta Tex-Mex', 'Concentrado de caldo de verduras', 'Cilantro', 'Chips de tortilla de maíz azul' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '510 kcal',
		nVfat: '15g',
		nVsaturatedFat: '2g',
		nVcarbohydrate: '77g',
		nVsugar: '16g',
		nVdietaryFiber: '16g',
		nVprotein: '19g',
		nVcholesterol: '0mg',
		nVsodium: '2.530mg',
	},
	{
		id: 17,
		itemName: 'Lo Mein de champigñones',
		stock: 20,
		price: 400,
		shortDescription: 'con Fideos Udon Frescos',
		description:
			'El lo mein al estilo chino adquiere un toque más abundante y saludable cuando cambias los sospechosos carnosos habituales por champiñones y verduras como zanahorias y judías verdes. En esta receta, practicará saltear fideos udon en salsa hasta que rebosen con un sabroso sabor a base de soya, hoisin y sésamo que estalla con cada bocado.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670650170/veggieBox/img/dishes/100x90/lo_mein_de_champignones_fxgzuv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670650118/veggieBox/img/dishes/525x350/lo_mein_de_champignones_ceat0s.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670650541/veggieBox/img/dishes/750x500/lo_mein_de_champignones_r7wufb.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670650148/veggieBox/img/dishes/310x207/lo_mein_de_champignones_icg6rt.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Champiñones', 'Arvejas', 'Zanahorias', 'Fideos Udon', 'Jengibre', 'Ajo', 'Concentrado de caldo de verduras', 'Eschalote', 'Salsa Hoisin', 'Salsa de soja', 'Aceite de sésamo' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '480 kcal',
		nVfat: '17g',
		nVsaturatedFat: '2g',
		nVcarbohydrate: '70g',
		nVsugar: '15g',
		nVdietaryFiber: '7g',
		nVprotein: '11g',
		nVcholesterol: '0mg',
		nVsodium: '900mg',
	},
	{
		id: 18,
		itemName: 'Bowls veganos de garbanzos con especias turcas',
		stock: 20,
		price: 400,
		shortDescription: 'con arroz basmati de pistacho y salsa de hummus de limón y hierbas',
		description:
			'Un tazón de garbanzos es el epítome de la perfección basada en plantas. En este, los garbanzos con especias turcas se tuestan junto con rodajas de cebolla y tomates uva, luego se mezclan con ralladura de limón brillante y picante. Las verduras se sirven sobre una cama de fragante arroz basmati mezclado con pistachos y pasas doradas para darle textura y dulzura. Y como el secreto siempre está en la salsa, terminarás con un chorrito de hummus de limón con hierbas que une todos estos sabores. Con tanto para saborear en un tazón, ¡garantizamos que los invitados a la cena no veganos ni siquiera extrañarán la carne!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670650170/veggieBox/img/dishes/100x90/lo_mein_de_champignones_fxgzuv.jpghttps://res.cloudinary.com/ferjen/image/upload/v1670651783/veggieBox/img/dishes/100x90/bowls_veganos_de_garbanzos_con_especias_turcas_kohcp0.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670651835/veggieBox/img/dishes/525x350/bowls_veganos_de_garbanzos_con_especias_turcas_w95cxp.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670651866/veggieBox/img/dishes/750x500/bowls_veganos_de_garbanzos_con_especias_turcas_tsoeta.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670651732/veggieBox/img/dishes/310x207/bowls_veganos_de_garbanzos_con_especias_turcas_jhcd1o.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Arroz Basmati', 'Garbanzos', 'Tomates de uva', 'Cebolla morada', 'Limón', 'Concentrado de caldo de verduras', 'Mezcla de especias turcas', 'Pistachos', 'Hummus', 'Ajo', 'Perejil', 'Ciboullette', 'Pasas doradas' ],
		cookingTime: 40,
		cookingDifficulty: 'Medio',
		nVcalories: '850 kcal',
		nVfat: '36g',
		nVsaturatedFat: '5g',
		nVcarbohydrate: '113g',
		nVsugar: '22g',
		nVdietaryFiber: '13g',
		nVprotein: '20g',
		nVcholesterol: '0mg',
		nVsodium: '940mg',
	},
	{
		id: 19,
		itemName: 'Tofu frito vegano con arroz de jardín cargado',
		stock: 20,
		price: 400,
		shortDescription: 'con salsa de chile dulce katsu',
		description:
			'El tierno tofu se transforma en la estrella del espectáculo en esta satisfactoria cena. Primero, se mezcla con una mezcla de harina y almidón de maíz y se fríe, transformándose en una golosina dorada, crocante y crujiente con un interior suave y esponjoso. El fragante arroz frito, adornado con zanahorias tiernas y crujientes y brillantes guisantes dulces y cebolletas, proporciona un lugar apropiado y sabroso para anidar el tofu. Termine con una llovizna de salsa katsu picante, dulce y salada y una pizca de cebolletas verdes.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670652984/veggieBox/img/dishes/100x90/tofu_frito_vegano_con_arroz_de_jard%C3%ADn_cargado_ceqbn2.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670653012/veggieBox/img/dishes/525x350/tofu_frito_vegano_con_arroz_de_jard%C3%ADn_cargado_vowqou.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670653038/veggieBox/img/dishes/750x500/tofu_frito_vegano_con_arroz_de_jard%C3%ADn_cargado_hhcwa6.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670653062/veggieBox/img/dishes/310x207/tofu_frito_vegano_con_arroz_de_jard%C3%ADn_cargado_myigk3.jpg',
		],
		categoryId: 5,
		category: {
			id: 5,
			categoryName: 'Vegano',
		},
		ingredients: [ 'Tofu', 'Cebolla amarilla', 'Zanahorias', 'Eschalot', 'Arroz Jazmín', 'Fo concentrado', 'Harina', 'Maicena', 'Guisantes', 'Aceite de sésamo', 'Soy Sauce', 'Salsa Katsu', 'Salsa hoisin', 'Salsa dulce de chile tailandés' ],
		cookingTime: 35,
		cookingDifficulty: 'Difícil',
		nVcalories: '1070 kcal',
		nVfat: '36g',
		nVsaturatedFat: '5g',
		nVcarbohydrate: '152g',
		nVsugar: '36g',
		nVdietaryFiber: '6g',
		nVprotein: '26g',
		nVcholesterol: '0mg',
		nVsodium: '2.710mg',
	},
	{
		id: 20,
		itemName: 'Proteína a base de plantas del sudoeste sobre arroz',
		stock: 20,
		price: 400,
		shortDescription: 'Proteína que sabe a carne (sin carne)',
		description:
			'¿Antojo de todos los tentadores sabores y texturas de un tazón de burrito, menos la carne? No busque más. Esta versión está protagonizada por proteína vegetal molida, que crujientes en una sartén caliente para obtener bordes caramelizados, luego cocinamos a fuego lento con poblano, cebolla y una gran cantidad de condimentos hasta que estén picantes. Todo se apila sobre arroz con cilantro y lima con tomate, cebolla en escabeche y crema de lima ácida. Ahora, ¿quién realmente necesita la carne cuando tienes todo eso?',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670655682/veggieBox/img/dishes/100x90/proteina_a_base_de_plantas_del_sudoeste_sobre_arroz_gtch9g.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670655721/veggieBox/img/dishes/525x350/proteina_a_base_de_plantas_del_sudoeste_sobre_arroz_kggbby.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670655745/veggieBox/img/dishes/750x500/proteina_a_base_de_plantas_del_sudoeste_sobre_arroz_pcadie.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670655698/veggieBox/img/dishes/310x207/proteina_a_base_de_plantas_del_sudoeste_sobre_arroz_jimnl3.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Arroz Jazmín', 'Cebolla morada', 'Lima', 'Chile poblano', 'Tomate Roma', 'Cilantro', 'Proteína de origen vegetal molida', 'Mezcla de especias del suroeste', 'Pasta Tex-Mex', 'Crema agria' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '670 kcal',
		nVfat: '27g',
		nVsaturatedFat: '11g',
		nVcarbohydrate: '88g',
		nVsugar: '8g',
		nVdietaryFiber: '7g',
		nVprotein: '16g',
		nVcholesterol: '65mg',
		nVsodium: '1.290mg',
	},
	{
		id: 21,
		itemName: 'Fajitas de batata',
		stock: 20,
		price: 400,
		shortDescription: 'con queso Pepper Jack, jalapeño en escabeche y crema de lima',
		description:
			'¿Qué hacen las batatas en una fajita, preguntas? ¡Todo, decimos! Estos sabrosos tubérculos repletos de vitamina A son la manera perfecta de hacer que la noche Tex-Mex no tenga carne. Después de cortarlos en gajos gruesos, les das un poco de especias calientes y los tuestas en el horno hasta que estén lo más tiernos posible. Y con la ayuda de algunos ingredientes muy satisfactorios (jalapeño en escabeche, cebolla y pimiento verde salteados, salsa de tomate y crema agria de lima), esta receta contiene todo lo que podrías desear dentro del pliegue de una tortilla.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670656572/veggieBox/img/dishes/100x90/fajitas_de_batata_nfre2j.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670656549/veggieBox/img/dishes/525x350/fajitas_de_batata_yitmxf.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670656537/veggieBox/img/dishes/750x500/fajitas_de_batata_endf6e.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670656560/veggieBox/img/dishes/310x207/fajitas_de_batata_oq9pza.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Batata', 'Mezcla de especias del suroeste', 'Cebolla morada', 'Pimiento Verde Largo', 'Tomate Perita', 'Lima', 'Cilantro', 'Jalapeño', 'Crmea agria', 'Tortillas de harina', 'Queso pimienta' ],
		cookingTime: 35,
		cookingDifficulty: 'Sencillo',
		nVcalories: '790 kcal',
		nVfat: '39g',
		nVsaturatedFat: '18g',
		nVcarbohydrate: '88g',
		nVsugar: '16g',
		nVdietaryFiber: '9g',
		nVprotein: '24g',
		nVcholesterol: '70mg',
		nVsodium: '1.410mg',
	},
	{
		id: 22,
		itemName: 'Pimientos Rellenos De Proteína De Origen Vegetal',
		stock: 20,
		price: 400,
		shortDescription: 'Proteína que sabe a carne (sin carne)',
		description:
			'Los pimientos rellenos son una de nuestras cenas reconfortantes favoritas de todos los tiempos: son dulces, salados, sustanciosos y se pueden personalizar infinitamente con diferentes rellenos y aderezos. Este riff en el clásico italiano está protagonizado por una proteína vegetal molida, que sazonamos con hierbas y especias toscanas, luego cocinamos a fuego lento con cuscús, pasta de tomate y tomate cortado en cubitos hasta que estén tiernos y llenos de sabor. Todo está relleno de pimientos, cubierto con mozzarella y asado hasta que se derrita. ¿Quién necesita la carne cuando tienes todo eso?',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670656957/veggieBox/img/dishes/100x90/pimientos_rellenos_de_proteina_de_origen_vegetal_ldnfup.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670656936/veggieBox/img/dishes/525x350/pimientos_rellenos_de_proteina_de_origen_vegetal_jzyudt.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670656925/veggieBox/img/dishes/750x500/pimientos_rellenos_de_proteina_de_origen_vegetal_q9ny7h.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670656947/veggieBox/img/dishes/310x207/pimientos_rellenos_de_proteina_de_origen_vegetal_z6scis.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Pimiento verde', 'Cebolla amarilla', 'Tomate Roma', 'Proteína de origen vegetal molida', 'Especias picantes toscanas', 'Pasta de tomate', 'Concentrado de caldo de verduras', 'Cuscús israelí', 'Queso mozzarella' ],
		cookingTime: 40,
		cookingDifficulty: 'Sencillo',
		nVcalories: '850 kcal',
		nVfat: '47g',
		nVsaturatedFat: '21g',
		nVcarbohydrate: '69g',
		nVsugar: '15g',
		nVdietaryFiber: '9g',
		nVprotein: '28g',
		nVcholesterol: '130mg',
		nVsodium: '1.310mg',
	},
	{
		id: 23,
		itemName: 'Cuencos de proteína a base de plantas de soja y jengibre',
		stock: 20,
		price: 400,
		shortDescription: 'Proteína que sabe a carne (sin carne)',
		description:
			'¿Desea todos los tentadores sabores y texturas de un tazón de arroz, menos la carne? No busque más. Esta versión está protagonizada por proteína vegetal molida, que crujientes en una sartén caliente para obtener bordes caramelizados, luego cocinamos a fuego lento con jengibre, ajo y cebolletas y una gran cantidad de salsa de soja dulce y chile. Todo se apila sobre arroz con cilantro y lima con cintas de pepino y zanahoria en escabeche y cacahuetes confitados crujientes. Ahora, ¿quién realmente necesita la carne cuando tienes todo eso?',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670657383/veggieBox/img/dishes/100x90/cuencos_de_proteina_a_base_de_plantas_de_soja_y_jengibre_t95yiv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670657368/veggieBox/img/dishes/525x350/cuencos_de_proteina_a_base_de_plantas_de_soja_y_jengibre_hdytwv.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670657363/veggieBox/img/dishes/750x500/cuencos_de_proteina_a_base_de_plantas_de_soja_y_jengibre_dh6fam.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670657375/veggieBox/img/dishes/310x207/cuencos_de_proteina_a_base_de_plantas_de_soja_y_jengibre_a1znek.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Arroz Jamaní', 'Zanahoria', 'pepino persa', 'Jengibre', 'Ajo', 'cebolletas', 'Cilantro', 'Proteína de origen vegetal molida', 'vinagre de vino de arroz', 'Salsa dulce de chile tailandés', 'Glaseado de soja dulce', 'Maní' ],
		cookingTime: 35,
		cookingDifficulty: 'Medio',
		nVcalories: '710 kcal',
		nVfat: '21g',
		nVsaturatedFat: '9g',
		nVcarbohydrate: '110g',
		nVsugar: '35g',
		nVdietaryFiber: '5g',
		nVprotein: '18g',
		nVcholesterol: '15mg',
		nVsodium: '1.860mg',
	},
	{
		id: 24,
		itemName: 'Rigatoni Alla Rossa de proteína vegetal',
		stock: 20,
		price: 400,
		shortDescription: 'Proteína que sabe a carne (sin carne)',
		description:
			'¿Anhelas la comodidad de una pasta sustanciosa y picante, sin carne? Te tenemos cubierto. Aquí, intercambiamos una proteína de origen vegetal molida, que salteamos con pimiento y cebolletas, luego cocinamos a fuego lento en una rica y cremosa salsa de tomate con hierbas. Se mezcla con fideos rigatoni al dente y luego se cubre con queso parmesano. ¿Quién necesita la carne cuando tienes todo eso?',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670659029/veggieBox/img/dishes/100x90/rigatoni_alla_rossa_de_prote%C3%ADna_vegetal_gio8g3.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670659051/veggieBox/img/dishes/525x350/rigatoni_alla_rossa_de_prote%C3%ADna_vegetal_ifnqzu.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670659060/veggieBox/img/dishes/750x500/rigatoni_alla_rossa_de_prote%C3%ADna_vegetal_yogu1m.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670659040/veggieBox/img/dishes/310x207/rigatoni_alla_rossa_de_prote%C3%ADna_vegetal_o2r0vd.jpg',
		],
		categoryId: 4,
		category: {
			id: 4,
			categoryName: 'Vegetariano',
		},
		ingredients: [ 'Proteína de origen vegetal molida', 'Pimiento morrón', 'Pasta Rigatoni', 'Pasta de tomate', 'Queso crema', 'Queso parmesano', 'Condimento italiano', 'Ciboullette' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '930 kcal',
		nVfat: '44g',
		nVsaturatedFat: '23g',
		nVcarbohydrate: '92g',
		nVsugar: '15g',
		nVdietaryFiber: '8g',
		nVprotein: '43g',
		nVcholesterol: '135mg',
		nVsodium: '1.010mg',
	},
	{
		id: 25,
		itemName: 'Cerdo al Mojo',
		stock: 20,
		price: 400,
		shortDescription: 'con Arroz Cubano y Porotos Negros',
		description:
			'Mojo es la versión cubana de la luz del sol en un plato: la salsa irradia sabor con sus vibrantes jugos cítricos, hierbas frescas y sabrosos trocitos de ajo. Cuando se rocía sobre tiernas chuletas de cerdo, el efecto es verdaderamente radiante. Para añadir las vibraciones cálidas, también estamos introduciendo rodajas de pimiento morrón y frijoles sabrosos con arroz. Si el clima ha estado un poco frío donde estás, este plato probablemente dará en el clavo y alegrará tu día.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670674055/veggieBox/img/dishes/100x90/cerdo_al_mojo_inrfhc.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670674074/veggieBox/img/dishes/525x350/cerdo_al_mojo_rneuyb.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670674083/veggieBox/img/dishes/750x500/cerdo_al_mojo_mei5wh.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670674063/veggieBox/img/dishes/310x207/cerdo_al_mojo_brsnu8.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Arroz basmati', 'Cilantro', 'Ajo', 'Pimiento morrón', 'Cebolla roja', 'Cebolla de verdeo', 'Naranja', 'Lima', 'Orégano', 'Carré de Cerdo', 'Concentrado de Caldo de Pollo', 'Mermelada de damazco', 'Porotos negros' ],
		cookingTime: 40,
		cookingDifficulty: 'Sencillo',
		nVcalories: '690 kcal',
		nVfat: '16g',
		nVsaturatedFat: '3,5g',
		nVcarbohydrate: '90g',
		nVsugar: '21g',
		nVdietaryFiber: '16g',
		nVprotein: '51g',
		nVcholesterol: '90mg',
		nVsodium: '540mg',
	},
	{
		id: 26,
		itemName: 'Cremoso bistec de Rib-Eye a la Bearnesa',
		stock: 20,
		price: 400,
		shortDescription: 'con papas alargadas, judías verdes salteadas y tomates',
		description:
			'El bistec y la bearnesa son lo más clásico francés posible. La salsa espesa y rica está acentuada con estragón y vinagre de vino blanco para darle un toque ligeramente agrio y herbáceo que se funde y combina armoniosamente con la carne de res. Para ayudar a aligerar las cosas contra toda esa decadencia, mantenemos los lados simples: patatas asadas y una mezcla de judías verdes y tomates que encaja perfectamente.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670674591/veggieBox/img/dishes/100x90/bistec_cremoso_de_rib-eye_a_la_bearnesa_u2ouou.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670674608/veggieBox/img/dishes/525x350/bistec_cremoso_de_rib-eye_a_la_bearnesa_xyoaa2.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670674616/veggieBox/img/dishes/750x500/bistec_cremoso_de_rib-eye_a_la_bearnesa_sxi1gn.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670674599/veggieBox/img/dishes/310x207/bistec_cremoso_de_rib-eye_a_la_bearnesa_tufanv.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Papines', 'Eschalot', 'Arvejas verdes', 'Estragón', 'Tomates', 'Vinagre de vino blanco', 'Mostaza de Dijon', 'Crema agria', 'Bistec corte Rib-eye' ],
		cookingTime: 45,
		cookingDifficulty: 'Sencillo',
		nVcalories: '950 kcal',
		nVfat: '69g',
		nVsaturatedFat: '28g',
		nVcarbohydrate: '45g',
		nVsugar: '11g',
		nVdietaryFiber: '9g',
		nVprotein: '36g',
		nVcholesterol: '160mg',
		nVsodium: '270mg',
	},
	{
		id: 27,
		itemName: 'Pollo con Salsa de Tomillo',
		stock: 20,
		price: 400,
		shortDescription: 'con Zanahorias Asadas y Patatas',
		description:
			'Las modas gastronómicas van y vienen. Pero algunas recetas son probadas, verdaderas y atemporales. Como este: pollo, zanahorias asadas y salsa son un trío que es lo mejor posible. Sin embargo, para animar un poco las cosas, presentamos puré de papas con queso parmesano y pimienta negra, un combo que se conoce en Italia como "cacio e pepe". Porque, oye, incluso un clásico puede mejorarse con los poderes mágicos del queso.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670675054/veggieBox/img/dishes/100x90/pollo_con_salsa_de_tomillo_ys0mn8.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670675070/veggieBox/img/dishes/525x350/pollo_con_salsa_de_tomillo_ekgtjo.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670675080/veggieBox/img/dishes/750x500/pollo_con_salsa_de_tomillo_xlstqw.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670675062/veggieBox/img/dishes/310x207/pollo_con_salsa_de_tomillo_bqnmb2.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Zanahorias', 'Ajo', 'Perejil', 'Papa roja', 'Pechugas de pollo', 'Tomillo', 'Pollo Demi-Glace', 'Leche', 'Queso parmesano' ],
		cookingTime: 45,
		cookingDifficulty: 'Sencillo',
		nVcalories: '620 kcal',
		nVfat: '26g',
		nVsaturatedFat: '13g',
		nVcarbohydrate: '54g',
		nVsugar: '12g',
		nVdietaryFiber: '4g',
		nVprotein: '47g',
		nVcholesterol: '155mg',
		nVsodium: '540mg',
	},
	{
		id: 28,
		itemName: 'Pollo bajo una manta de calabacín',
		stock: 20,
		price: 400,
		shortDescription: 'con Puré de Papapas y Arvejas',
		description:
			'La capa de calabacín que cubre estas pechugas de pollo es como una manta que mantiene la carne caliente y acogedora mientras descansa su belleza. No solo aporta algunas verduras adicionales a esta receta, sino que también ayuda a que el pollo se mantenga húmedo y tierno. Siéntase libre de tratar el puré de papas a un lado como una almohada esponjosa para soñar sueños de puré de papas dulces y mantecosos.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670675873/veggieBox/img/dishes/100x90/pollo_bajo_una_manta_de_calabacin_ufpusy.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670675890/veggieBox/img/dishes/525x350/pollo_bajo_una_manta_de_calabacin_vp1zbg.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670675897/veggieBox/img/dishes/750x500/pollo_bajo_una_manta_de_calabacin_ar90ve.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670675882/veggieBox/img/dishes/310x207/pollo_bajo_una_manta_de_calabacin_xbh46g.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Papas Doradas', 'Zucchini', 'Queso parmesano', 'Pechugas de pollo', 'Arvejas', 'Leche', 'Limón' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '510 kcal',
		nVfat: '20g',
		nVsaturatedFat: '9g',
		nVcarbohydrate: '43g',
		nVsugar: '10g',
		nVdietaryFiber: '10g',
		nVprotein: '47g',
		nVcholesterol: '135mg',
		nVsodium: '290mg',
	},
	{
		id: 29,
		itemName: 'Bistec y Patatas con Estilo',
		stock: 20,
		price: 400,
		shortDescription: 'Rociados con salsa balsámica de arándanos rojos y repollo picante',
		description:
			'El bistec, el repollo y las papas pueden parecer una combinación simple. Nuestra versión, sin embargo, es todo lo contrario. Le hemos dado nueva vida al presentarle una salsa construida con vinagre balsámico y soya, que aporta una intensidad sabrosa y ácida; considéralo como una mezcla intercontinental entre sabores de inspiración italiana y asiática. Y con una pizca de romero fresco en las papas, también obtienes aromas increíbles que saltan del plato incluso antes de que hayas probado.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670677296/veggieBox/img/dishes/100x90/bistec_y_patatas_con_estilo_dfvv8k.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670677314/veggieBox/img/dishes/525x350/bistec_y_patatas_con_estilo_dx65ml.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670677324/veggieBox/img/dishes/750x500/bistec_y_patatas_con_estilo_uqvmuu.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670677303/veggieBox/img/dishes/310x207/bistec_y_patatas_con_estilo_fuocja.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Cebolla amarilla', 'Romero', 'Patatas Yukón Doradas', 'Repollo rojo rallado', 'Semillas de mostaza', 'Vinagre de vino blanco', 'Solomillo', 'Vinagre balsámico', 'Salsa de Soja', 'Mermelada de arándano' ],
		cookingTime: 40,
		cookingDifficulty: 'Sencillo',
		nVcalories: '680 kcal',
		nVfat: '34g',
		nVsaturatedFat: '11g',
		nVcarbohydrate: '57g',
		nVsugar: '15g',
		nVdietaryFiber: '8g',
		nVprotein: '37g',
		nVcholesterol: '120mg',
		nVsodium: '950mg',
	},
	{
		id: 30,
		itemName: 'Sopa de tortilla a la olla',
		stock: 20,
		price: 400,
		shortDescription: 'con Porotos Negros, Maíz, Pimiento Morrón y Aguacate',
		description:
			'La sopa de tortilla es uno de los clásicos de la cocina tradicional mexicana por una buena razón: es tan reconfortante y acogedora como la típica sopa de tomate y verduras, pero con el crujido de las tortillas crujientes y un toque picante adicional. Nuestra versión también presenta frijoles negros y maíz para que sea más abundante, además de aguacate y queso cheddar para un final cremoso.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670678324/veggieBox/img/dishes/100x90/sopa_de_tortilla_a_la_olla_cz1eld.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670678341/veggieBox/img/dishes/525x350/sopa_de_tortilla_a_la_olla_tyuryp.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670678350/veggieBox/img/dishes/750x500/sopa_de_tortilla_a_la_olla_fqj8hl.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670678334/veggieBox/img/dishes/310x207/sopa_de_tortilla_a_la_olla_aknyyk.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Cebolla amarilla', 'Pimiento verde', 'Ajo', 'Jalapeño', 'Porotos negros', 'Maíz', 'Tortilla Chips', 'Mezcla de Especias Mexicanas', 'Tomates aplastados', 'Concentrado de caldo de verduras', 'Palta', 'Queso cheddar' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '810 kcal',
		nVfat: '36g',
		nVsaturatedFat: '8g',
		nVcarbohydrate: '89g',
		nVsugar: '14g',
		nVdietaryFiber: '31g',
		nVprotein: '33g',
		nVcholesterol: '25mg',
		nVsodium: '880mg',
	},
	{
		id: 31,
		itemName: 'Tagliata de bistec en rodajas',
		stock: 20,
		price: 400,
		shortDescription: 'con papas dulces, arvejas verdes y vinagreta de tomate',
		description:
			'Tagliata proviene de la palabra italiana para "cortar", refiriéndose al hecho de que este bistec siempre se sirve en rodajas. La leyenda incluso dice que el plato se originó con una mujer noble particularmente perspicaz que exigió que sus sirvientes hicieran el tallado por ella. Cumplimos con su pedido cortando el solomillo antes de servirlo y rociándolo con una salsa balsámica, que gotea sobre los gajos de batata, empapándolos en suculentos jugos.',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670678789/veggieBox/img/dishes/100x90/tagliata_de_bistec_en_rodajas_tbbazc.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670678800/veggieBox/img/dishes/525x350/tagliata_de_bistec_en_rodajas_wqd5cw.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670678810/veggieBox/img/dishes/750x500/tagliata_de_bistec_en_rodajas_jeijw9.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670678793/veggieBox/img/dishes/310x207/tagliata_de_bistec_en_rodajas_cchd17.jpg',
		],
		categoryId: 3,
		category: {
			id: 3,
			categoryName: 'Sin Gluten',
		},
		ingredients: [ 'Batata', 'Romero', 'Ajo', 'Tomates de uva', 'Bistec ranchero', 'Avejas verdes', 'Vinagre balsámico', 'Concentrado de caldo de res' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '370 kcal',
		nVfat: '40g',
		nVsaturatedFat: '15g',
		nVcarbohydrate: '48g',
		nVsugar: '14g',
		nVdietaryFiber: '9g',
		nVprotein: '29g',
		nVcholesterol: '135mg',
		nVsodium: '580mg',
	},
	{
		id: 32,
		itemName: 'Carré de Cerdo Trattoria',
		stock: 20,
		price: 400,
		shortDescription: 'con zanahorias asadas, cuscús de ajo y salsa cremosa de tomate',
		description:
			'Las chuletas de cerdo son una idea ideal para cenar entre semana. Pero, ¿cómo elevas este modo de espera al sabor del nivel de un restaurante? Dilo conmigo: ¡SALSA! Y este es un sabroso, umami, picante: el eschalot y el ajo se doran y se vuelven carmelosos, luego invita a la pasta de tomate picante, el caldo de res umami y la crema agria a la fiesta de la sartén. Esta delicia se sirve con una cuchara sobre un carré de cerdo bien cubierto y sazonado, sobre una cama de cuscús con ajo junto a tiernas zanahorias asadas: ¡no te vas a dar cuenta que y light!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670681169/veggieBox/img/dishes/100x90/carre_de_cerdo_trattoria_ctvyjp.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670681184/veggieBox/img/dishes/525x350/carre_de_cerdo_trattoria_n2cm9p.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670681192/veggieBox/img/dishes/750x500/carre_de_cerdo_trattoria_fks7au.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670681177/veggieBox/img/dishes/310x207/carre_de_cerdo_trattoria_uom06j.jpg',
		],
		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Zanahorias', 'Ajo', 'Eschalot', 'Perejil', 'Cuscús israelí', 'Concentrado de caldo de res', 'Chuletas De Cerdo', 'Condimento italiano', 'Pasta de tomate', 'Crema agria' ],
		cookingTime: 35,
		cookingDifficulty: 'Medio',
		nVcalories: '640 kcal',
		nVfat: '32g',
		nVsaturatedFat: '13g',
		nVcarbohydrate: '57g',
		nVsugar: '15g',
		nVdietaryFiber: '7g',
		nVprotein: '35g',
		nVcholesterol: '110mg',
		nVsodium: '1.290mg',
	},
	{
		id: 33,
		itemName: 'Hamburguesas de Pavo con Jengibre y Ponzu',
		stock: 20,
		price: 400,
		shortDescription: 'con ensalada de repollo con brócoli y mayonesa de ají dulce',
		description:
			'Ah, la humilde hamburguesa de pavo. Simple, adaptable, sabroso, en serio, ¿qué no es amar? En este plato, las empanadas se infunden con jengibre fresco y salsa picante ponzu, luego se rocían con una mayonesa de chile dulce y se adornan con cebolletas. A un lado, el brócoli asado y el repollo rojo se mezclan con salsa de chile y aderezo de sésamo para una ensalada crujiente y colorida. Y, para el último truco de la hamburguesa (¿ves lo que hicimos allí?), tendrás todo emplatado en unos 30 minutos. ¡Gana entre semana!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670683313/veggieBox/img/dishes/100x90/hamburguesas_de_pavo_con_jengibre_y_ponzu_fe2wl7.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670683330/veggieBox/img/dishes/525x350/hamburguesas_de_pavo_con_jengibre_y_ponzu_bfnixq.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670683339/veggieBox/img/dishes/750x500/hamburguesas_de_pavo_con_jengibre_y_ponzu_khaxgb.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670683322/veggieBox/img/dishes/310x207/hamburguesas_de_pavo_con_jengibre_y_ponzu_f4omys.jpg',
		],
		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Flores de brócoli', 'Jengibre', 'cebolletas', 'Mayonesa', 'Salsa dulce de chile tailandés', 'Pavo molido', 'Salsa Ponzu', 'Fo concentrado', 'Migas de pan Panko', 'Repollo rojo rallado', 'Aderezo De Sésamo' ],
		cookingTime: 30,
		cookingDifficulty: 'Sencillo',
		nVcalories: '640 kcal',
		nVfat: '3g',
		nVsaturatedFat: '7g',
		nVcarbohydrate: '41g',
		nVsugar: '19g',
		nVdietaryFiber: '5g',
		nVprotein: '34g',
		nVcholesterol: '115mg',
		nVsodium: '1.610mg',
	},
	{
		id: 34,
		itemName: 'Espaguetis a la Griega con Queso Feta',
		stock: 20,
		price: 400,
		shortDescription: 'cubierto con espinacas, tomate, cebolletas y eneldo',
		description:
			'¿Qué obtienes cuando combinas sabores griegos brillantes y audaces con la simplicidad del espagueti? ¡Este plato de pasta es fantástico! Una salsa exuberante y cremosa está impregnada de queso feta salado, aromáticas hierbas mediterráneas y limón alegre, luego se mezcla con espagueti al dente, tomate y espinacas tiernas. ¿El toque final? Más hierbas, hojas de cebolleta y, por supuesto, ¡todo es mejor con más queso feta!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670683858/veggieBox/img/dishes/100x90/espaguetis_a_la_griega_con_queso_feta_m78esr.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670683875/veggieBox/img/dishes/525x350/espaguetis_a_la_griega_con_queso_feta_n0jhrn.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670683915/veggieBox/img/dishes/750x500/espaguetis_a_la_griega_con_queso_feta_pkz2e1.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670683866/veggieBox/img/dishes/310x207/espaguetis_a_la_griega_con_queso_feta_edjwxi.jpg',
		],
		categoryId: 2,
		category: {
			id: 2,
			categoryName: 'Light',
		},
		ingredients: [ 'Ajo', 'Cebollas de verdeo', 'Eneldo', 'Tomate', 'Limón', 'Espaguetis', 'Orégano seco', 'Concentrado de caldo de verduras', 'Queso crema', 'Queso Feta', 'Espinaca' ],
		cookingTime: 25,
		cookingDifficulty: 'Sencillo',
		nVcalories: '550 kcal',
		nVfat: '17g',
		nVsaturatedFat: '7g',
		nVcarbohydrate: '86g',
		nVsugar: '11g',
		nVdietaryFiber: '8g',
		nVprotein: '19g',
		nVcholesterol: '35mg',
		nVsodium: '810mg',
	},
	{
		id: 35,
		itemName: 'Lomo de Cerdo con Especias a la Mexicana',
		stock: 20,
		price: 400,
		shortDescription: 'con salsa de ananá asado y ensalada de verduras mixtas',
		description:
			'A la carne de cerdo de sabor suave le encanta algo dulce, que creemos que combina maravillosamente con el calor picante. ¡Qué suerte, la cena de esta noche lo tiene todo! El suculento lomo de cerdo se sella con nuestra mezcla de especias mexicanas, se asa a la perfección y se cubre con una increíble salsa de piña carbonizada y jalapeño. Agregamos un sabor más fresco con verduras tiernas vestidas con un aderezo cremoso y especiado. ¡Saludos a las parejas perfectas!',
		servings: 2,
		image: [
			'https://res.cloudinary.com/ferjen/image/upload/v1670684337/veggieBox/img/dishes/100x90/lomo_de_cerdo_con_especias_a_la_mexicana_xtpz5a.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670684356/veggieBox/img/dishes/525x350/lomo_de_cerdo_con_especias_a_la_mexicana_ieoym8.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670684365/veggieBox/img/dishes/750x500/lomo_de_cerdo_con_especias_a_la_mexicana_xj6uta.jpg',
			'https://res.cloudinary.com/ferjen/image/upload/v1670684347/veggieBox/img/dishes/310x207/lomo_de_cerdo_con_especias_a_la_mexicana_yqc7pe.jpg',
		],
		categoryId: 1,
		category: {
			id: 1,
			categoryName: 'Keto',
		},
		ingredients: [ 'Lomo de cerdo', 'Lima', 'Mayonesa', 'Piña', 'Mezcla de Especias Mexicanas', 'Jalapeño', 'Cebolla morada', 'Verduras mixtas', 'Crema agria' ],
		cookingTime: 40,
		cookingDifficulty: 'Medio',
		nVcalories: '530 kcal',
		nVfat: '11g',
		nVsaturatedFat: '9g',
		nVcarbohydrate: '19g',
		nVsugar: '11g',
		nVdietaryFiber: '2g',
		nVprotein: '28g',
		nVcholesterol: '130mg',
		nVsodium: '200mg',
	},

];
